name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm run install:all
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '#skip')
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
